In [1]:
import numpy as np 
import pandas as pd

In [11]:
data= pd.read_csv("matches - matches.csv")
data

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [17]:
data.head(5)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [18]:
import numpy as np
import pandas as pd

In [19]:
pd.read_csv('matches - matches.csv')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [20]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [29]:
data.tail(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [31]:
data.shape

(636, 18)

In [36]:
data.shape[0]

636

In [37]:
 data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

In [38]:
data.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [39]:
pd.read_csv('matches - matches.csv')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [40]:
data["city"]

0      Hyderabad
1           Pune
2         Rajkot
3         Indore
4      Bangalore
         ...
631       Raipur
632    Bangalore
633        Delhi
634        Delhi
635    Bangalore
Name: city, Length: 636, dtype: object

In [72]:
data[["city","team1","team2"]]

          city                        team1                        team2
0    Hyderabad          Sunrisers Hyderabad  Royal Challengers Bangalore
1         Pune               Mumbai Indians       Rising Pune Supergiant
2       Rajkot                Gujarat Lions        Kolkata Knight Riders
3       Indore       Rising Pune Supergiant              Kings XI Punjab
4    Bangalore  Royal Challengers Bangalore             Delhi Daredevils
..         ...                          ...                          ...
631     Raipur             Delhi Daredevils  Royal Challengers Bangalore
632  Bangalore                Gujarat Lions  Royal Challengers Bangalore
633      Delhi          Sunrisers Hyderabad        Kolkata Knight Riders
634      Delhi                Gujarat Lions          Sunrisers Hyderabad
635  Bangalore          Sunrisers Hyderabad  Royal Challengers Bangalore

[636 rows x 3 columns]

## ILOC

In [47]:
data.iloc[0]

id                                                         1
season                                                  2017
city                                               Hyderabad
date                                              2017-04-05
team1                                    Sunrisers Hyderabad
team2                            Royal Challengers Bangalore
toss_winner                      Royal Challengers Bangalore
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                               35
win_by_wickets                                             0
player_of_match                                 Yuvraj Singh
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                          AY Dandekar
umpire2                                             NJ Llong
umpire3                                                  NaN
Name: 0, dtype: object

## pattern based

In [71]:
data.iloc[0]

id                                                         1
season                                                  2017
city                                               Hyderabad
date                                              2017-04-05
team1                                    Sunrisers Hyderabad
team2                            Royal Challengers Bangalore
toss_winner                      Royal Challengers Bangalore
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                               35
win_by_wickets                                             0
player_of_match                                 Yuvraj Singh
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                          AY Dandekar
umpire2                                             NJ Llong
umpire3                                                  NaN
Name: 0, dtype: object

In [74]:
data.iloc[0:5]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [78]:
data.iloc[0:30:2]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
10,11,2017,Kolkata,2017-04-13,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
12,13,2017,Rajkot,2017-04-14,Rising Pune Supergiant,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,7,AJ Tye,Saurashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
14,15,2017,Delhi,2017-04-15,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
16,17,2017,Bangalore,2017-04-16,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rising Pune Supergiant,27,0,BA Stokes,M Chinnaswamy Stadium,KN Ananthapadmanabhan,C Shamshuddin,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
20,21,2017,Hyderabad,2017-04-19,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN
22,23,2017,Kolkata,2017-04-21,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,4,SK Raina,Eden Gardens,CB Gaffaney,Nitin Menon,NaN
24,25,2017,Pune,2017-04-22,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN
26,27,2017,Kolkata,2017-04-23,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN
28,29,2017,Pune,2017-04-26,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,RV Uthappa,Maharashtra Cricket Association Stadium,AY Dandekar,NJ Llong,NaN

## beyond pattern

In [83]:
data.iloc[[2,3,67]]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
67,68,2008,Hyderabad,2008-04-24,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,MR Benson,NaN

# for column

In [86]:
data.iloc[:,[2,3,6]]

          city        date                  toss_winner
0    Hyderabad  2017-04-05  Royal Challengers Bangalore
1         Pune  2017-04-06       Rising Pune Supergiant
2       Rajkot  2017-04-07        Kolkata Knight Riders
3       Indore  2017-04-08              Kings XI Punjab
4    Bangalore  2017-04-08  Royal Challengers Bangalore
..         ...         ...                          ...
631     Raipur  2016-05-22  Royal Challengers Bangalore
632  Bangalore  2016-05-24  Royal Challengers Bangalore
633      Delhi  2016-05-25        Kolkata Knight Riders
634      Delhi  2016-05-27          Sunrisers Hyderabad
635  Bangalore  2016-05-29          Sunrisers Hyderabad

[636 rows x 3 columns]

## Masking

In [90]:
mask=data['city']=="Hyderabad"
data[mask].shape[0]

49

In [103]:
def fetch_city (city):
    mask=data['city']==city
    return data[mask].shape[0]

In [104]:
fetch_city("Hyderabad")

49

In [113]:
mask1=data["city"]=="Bangalore"
mask2=data["toss_decision"]=='field'
data[mask1 & mask2].shape[0]

57

In [117]:
data["winner"].value_counts()

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [120]:
data["city"].value_counts()

city
Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Ahmedabad         12
Centurion         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Cape Town          7
Abu Dhabi          7
Ranchi             7
Port Elizabeth     7
Cuttack            7
Raipur             6
Sharjah            6
Kochi              5
Indore             5
Kanpur             4
Nagpur             3
Kimberley          3
East London        3
Bloemfontein       2
Name: count, dtype: int64

In [123]:
data["toss_decision"].value_counts()

toss_decision
field    363
bat      273
Name: count, dtype: int64

# series operation

In [136]:
s=data["winner"].value_counts()
s.index

Index(['Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders',
       'Royal Challengers Bangalore', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Sunrisers Hyderabad', 'Deccan Chargers',
       'Gujarat Lions', 'Pune Warriors', 'Rising Pune Supergiant',
       'Kochi Tuskers Kerala', 'Rising Pune Supergiants'],
      dtype='object', name='winner')

In [137]:
s.values

array([92, 79, 77, 73, 70, 63, 62, 42, 29, 13, 12, 10,  6,  5],
      dtype=int64)

In [138]:
s["Mumbai Indians"]

92

In [139]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [142]:
data['team1'].value_counts()+data["team2"].value_counts()

Chennai Super Kings            131
Deccan Chargers                 75
Delhi Daredevils               147
Gujarat Lions                   30
Kings XI Punjab                148
Kochi Tuskers Kerala            14
Kolkata Knight Riders          148
Mumbai Indians                 157
Pune Warriors                   46
Rajasthan Royals               118
Rising Pune Supergiant          16
Rising Pune Supergiants         14
Royal Challengers Bangalore    152
Sunrisers Hyderabad             76
Name: count, dtype: int64

In [146]:
data["player_of_match"].value_counts()

player_of_match
CH Gayle          18
YK Pathan         16
DA Warner         15
AB de Villiers    15
RG Sharma         14
                  ..
AD Mathews         1
LR Shukla          1
R Bhatia           1
A Singh            1
BCJ Cutting        1
Name: count, Length: 201, dtype: int64

## the sort_values() function

In [157]:
data["winner"].value_counts().sort_values(ascending=False)

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [155]:
data.sort_values("winner",ascending=False)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
46,47,2017,Hyderabad,2017-05-08,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,normal,0,Sunrisers Hyderabad,0,7,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",KN Ananthapadmanabhan,M Erasmus,NaN
502,503,2014,Hyderabad,2014-05-20,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,bat,normal,0,Sunrisers Hyderabad,0,7,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,NJ Llong,NaN
488,489,2014,Delhi,2014-05-10,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,1,Sunrisers Hyderabad,0,8,DW Steyn,Feroz Shah Kotla,RM Deshpande,BNJ Oxenford,NaN
486,487,2014,Ahmedabad,2014-05-08,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,normal,0,Sunrisers Hyderabad,32,0,B Kumar,"Sardar Patel Stadium, Motera",AK Chaudhary,NJ Llong,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,547,2015,Chennai,2015-04-28,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Chennai Super Kings,2,0,DJ Bravo,"MA Chidambaram Stadium, Chepauk",RM Deshpande,VA Kulkarni,NaN
489,490,2014,Mumbai,2014-05-10,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,4,DR Smith,Wankhede Stadium,HDPK Dharmasena,VA Kulkarni,NaN
300,301,2011,Delhi,2011-05-21,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,no result,0,NaN,0,0,NaN,Feroz Shah Kotla,SS Hazare,RJ Tucker,NaN
545,546,2015,Bangalore,2015-04-29,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,JD Cloete,PG Pathak,NaN
570,571,2015,Bangalore,2015-05-17,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,HDPK Dharmasena,K Srinivasan,NaN

In [163]:
data.sort_values(["city","date"],ascending=[True,False])

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
475,476,2014,Abu Dhabi,2014-04-29,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,tie,0,Rajasthan Royals,0,0,JP Faulkner,Sheikh Zayed Stadium,Aleem Dar,AK Chaudhary,NaN
470,471,2014,Abu Dhabi,2014-04-26,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,6,PV Tambe,Sheikh Zayed Stadium,HDPK Dharmasena,C Shamshuddin,NaN
471,472,2014,Abu Dhabi,2014-04-26,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kings XI Punjab,23,0,Sandeep Sharma,Sheikh Zayed Stadium,HDPK Dharmasena,RK Illingworth,NaN
464,465,2014,Abu Dhabi,2014-04-21,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Chennai Super Kings,93,0,SK Raina,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
459,460,2014,Abu Dhabi,2014-04-18,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,469,2014,NaN,2014-04-25,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,4,0,AJ Finch,Dubai International Cricket Stadium,M Erasmus,S Ravi,NaN
469,470,2014,NaN,2014-04-25,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Chennai Super Kings,0,7,MM Sharma,Dubai International Cricket Stadium,BF Bowden,M Erasmus,NaN
466,467,2014,NaN,2014-04-23,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Chennai Super Kings,7,0,RA Jadeja,Dubai International Cricket Stadium,HDPK Dharmasena,RK Illingworth,NaN
461,462,2014,NaN,2014-04-19,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,PA Patel,Dubai International Cricket Stadium,Aleem Dar,AK Chaudhary,NaN
462,463,2014,NaN,2014-04-19,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,normal,0,Delhi Daredevils,0,4,JP Duminy,Dubai International Cricket Stadium,Aleem Dar,VA Kulkarni,NaN

In [3]:
company=pd.read_csv('Fortune 500 2017 - Fortune 500.csv')

In [5]:
company.shape

(500, 23)

In [173]:
company.head(2)

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0

In [6]:
company.groupby("Sector")

In [178]:
len(company)

500

In [7]:
sectors=company.groupby("Sector")

In [185]:
len(sectors)

21

In [187]:
   sectors.first()

,Rank,Title,Website,Employees,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Sector,,,,,,,,,,,,,,,,,,,,,
Aerospace & Defense,24,Boeing,http://www.boeing.com,150540,Aerospace and Defense,"Chicago, IL",100 N. Riverside Plaza,Chicago,IL,60606,...,"Chairman, President & Chief Executive Officer","100 N. Riverside Plaza, Chicago, IL 60606",BA,The Boeing Company,94571,-1.6,4895.0,-5.4,89997,817.0
Apparel,88,Nike,http://www.nike.com,70700,Apparel,"Beaverton, OR",1 Bowerman Dr.,Beaverton,OR,97005,...,"Chairman, President & Chief Executive Officer","1 Bowerman Dr., Beaverton, OR 97005",NKE,"Nike, Inc.",32376,5.8,3760.0,14.9,21396,12258.0
Business Services,146,ManpowerGroup,http://www.manpowergroup.com,28000,Temporary Help,"Milwaukee, WI",100 Manpower Place,Milwaukee,WI,53212,...,Chairman & Chief Executive Officer,"100 Manpower Place, Milwaukee, WI 53212",MAN,ManpowerGroup Inc.,19654,1.7,443.7,5.8,7574,2362.0
Chemicals,62,Dow Chemical,http://www.dow.com,56000,Chemicals,"Midland, MI",2030 Dow Center,Midland,MI,48674,...,Chairman & Chief Executive Officer,"2030 Dow Center, Midland, MI 48674",DOW,The Dow Chemical Company,48158,-1.3,4318.0,-43.8,79511,25987.0
Energy,4,Exxon Mobil,http://www.exxonmobil.com,72700,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,75039,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
Engineering & Construction,149,Fluor,http://www.fluor.com,61551,"Engineering, Construction","Irving, TX",6700 Las Colinas Blvd.,Irving,TX,75039,...,Chairman & Chief Executive Officer,"6700 Las Colinas Blvd., Irving, TX 75039",FLR,Fluor Corporation,19037,5.1,281.4,-31.8,9216,3125.0
Financials,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,68131,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
Food & Drug Stores,17,Walgreens Boots Alliance,http://www.walgreensbootsalliance.com,300000,Food and Drug Stores,"Deerfield, IL",108 Wilmot Rd.,Deerfield,IL,60015,...,"President, Chief Executive Officer & Director","108 Wilmot Rd., Deerfield, IL 60015",WBA,"Walgreens Boots Alliance, Inc",117351,13.4,4173.0,-1.1,72688,29880.0
"Food, Beverages & Tobacco",44,PepsiCo,http://www.pepsico.com,264000,Food Consumer Products,"Purchase, NY",700 Anderson Hill Rd.,Purchase,NY,10577,...,Chairman & Chief Executive Officer,"700 Anderson Hill Rd., Purchase, NY 10577",PEP,"PepsiCo, Inc.",62799,-0.4,6329.0,16.1,74129,11095.0
Health Care,6,UnitedHealth Group,http://www.unitedhealthgroup.com,230000,Health Care: Insurance and Managed Care,"Minnetonka, MN",9900 Bren Rd. E.,Minnetonka,MN,55343,...,Chief Executive Officer & Director,"9900 Bren Rd. E., Minnetonka, MN 55343",UNH,UnitedHealth Group Incorporated,184840,17.7,7017.0,20.7,122810,38274.0
"Hotels, Restaurants & Leisure",112,McDonaldâ€™s,http://www.aboutmcdonalds.com,375000,Food Services,"Oak Brook, IL",1 McDonald's Plaza,Oak Brook,IL,60523,...,"President, Chief Executive Officer & Director","1 McDonald's Plaza, Oak Brook, IL 60523",MCD,McDonald's Corporation,24622,-3.1,4686.5,3.5,31024,-2204.0
Household Products,36,Procter & Gamble,http://www.pg.com,105000,Household and Personal Products,"Cincinnati, OH",1 Procter & Gamble Plaza,Cincinnati,OH,45202,...,"Chairman, President & Chief Executive Officer","1 Procter & Gamble Plaza, Cincinnati, OH 45202",PG,The Procter & Gamble Company,71726,-8.9,10508.0,49.3,127136,57341.0
Industrials,13,General Electric,http://www.ge.com,295000,Industrial Machinery,"Boston, MA",41 Farnsworth St.,Boston,MA,2210,...,Chairman & Chief Executive Officer,"41 Farnsworth St., Boston, MA 02210",GE,General Electric Company,126661,-9.8,8831.0,297.8,365183,75828.0
Materials,133,International Paper,http://www.internationalpaper.com,55000,"Packaging, Containers","Memphis, TN",6400 Poplar Ave.,Memphis,TN,38197,...,Chairman & Chief Executive Officer,"6400 Poplar Ave., Memphis, TN 38197",IP,International Paper Company,21079,-5.8,904.0,-3.6,33345,4341.0
Media,52,Disney,http://www.disney.com,195000,Entertainment,"Burbank, CA",500 S. Buena Vista St.,Burbank,CA,91521,...,Chairman & Chief Executive Officer,"500 S. Buena Vista St., Burbank, CA 91521",DIS,The Walt Disney Company,55632,6.0,9391.0,12,92033,43265.0
Motor Vehicles & Parts,8,General Motors,http://www.gm.com,225000,Motor Vehicles and Parts,"Detroit, MI",300 Renaissance Center,Detroit,MI,48265,...,Chairman & Chief Executive Officer,"300 Renaissance Center, Detroit, MI 48265",GM,General Motors Company,166380,9.2,9427.0,-2.7,221690,43836.0
Retailing,1,Walmart,http://www.walmart.com,2300000,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,72716,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
Technology,3,Apple,http://www.apple.com,116000,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,95014,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
Telecommunications,9,AT&T,http://www.att.com,268540,Telecommunications,"Dallas, TX",208 S. Akard St.,Dallas,TX,75202,...,"Chairman, President & Chief Executive Officer","208 S. Akard St., Dallas, TX 75202",T,AT&T Inc.,163786,11.6,12976.0,-2.8,403821,123135.0
Transportation,46,UPS,http://www.ups.com,335520,"Mail, Package, and Freight Delivery","Atlanta, GA",55 Glenlake Pkwy. N.E.,Atlanta,GA,30328,...,Chairman & Chief Executive Officer,"55 Glenlake Pkwy. N.E., Atlanta, GA 30328",UPS,"United Parcel Service, Inc.",60906,4.4,3431.0,-29.2,40377,405.0
Wholesalers,5,McKesson,http://www.mckesson.com,68000,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,94104,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [188]:
sectors.last()

,Rank,Title,Website,Employees,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Sector,,,,,,,,,,,,,,,,,,,,,
Aerospace & Defense,492,Rockwell Collins,http://www.rockwellcollins.com,19000,Aerospace and Defense,"Cedar Rapids, IA",400 Collins Rd. N.E.,Cedar Rapids,IA,52498,...,"Chairman, President & Chief Executive Officer","400 Collins Rd. N.E., Cedar Rapids, IA 52498",COL,"Rockwell Collins, Inc.",5259,-0.1,728.0,6.1,7707,2078.0
Apparel,432,Hanesbrands,http://www.hanes.com,67800,Apparel,"Winston-Salem, NC",1000 E. Hanes Mill Rd.,Winston-Salem,NC,27105,...,Chief Executive Officer & Director,"1000 E. Hanes Mill Rd., Winston-Salem, NC 27105",HBI,Hanesbrands Inc.,6063,5.8,539.4,25.8,6908,1224.0
Business Services,500,ABM Industries,http://www.abm.com,110000,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,10006,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0
Chemicals,484,Celanese,http://www.celanese.com,7293,Chemicals,"Irving, TX",222 W. Las Colinas Blvd.,Irving,TX,75039,...,"Chairman, President & Chief Executive Officer","222 W. Las Colinas Blvd., Irving, TX 75039",CE,Celanese Corporation,5389,-5.0,900.0,196.1,8357,2588.0
Energy,499,Vistra Energy,http://www.vistraenergy.com,4431,Energy,"Dallas, TX",1601 Bryan St.,Dallas,TX,75201,...,"President, Chief Executive Officer & Director","1601 Bryan St., Dallas, TX 75201",VST,Vistra Energy Corp.,5164,4.0,-214.3,5.2,15167,6597.0
Engineering & Construction,497,Toll Brothers,http://www.tollbrothers.com,4200,Homebuilders,"Horsham, PA",250 Gibraltar Rd.,Horsham,PA,19044,...,Chief Executive Officer & Director,"250 Gibraltar Rd., Horsham, PA 19044",TOL,"Toll Brothers, Inc.",5170,23.9,382.1,5.2,9737,4229.0
Financials,483,Western & Southern Financial Group,http://www.westernsouthern.com,2178,"Insurance: Life, Health (Mutual)","Cincinnati, OH",400 Broadway,Cincinnati,OH,45202,...,"Chairman, President & Chief Executive Officer","400 Broadway, Cincinnati, OH 45202",CC,Western & Southern Mutual Holding Company,5398,0.8,241.2,-47.2,43831,5104.0
Food & Drug Stores,176,Whole Foods Market,http://www.wholefoodsmarket.com,73515,Food and Drug Stores,"Austin, TX",550 Bowie St.,Austin,TX,78703,...,Chief Executive Officer & Director,"550 Bowie St., Austin, TX 78703",WFM,"Whole Foods Market, Inc.",15724,2.2,507.0,-5.4,6341,3224.0
"Food, Beverages & Tobacco",486,Seaboard,http://www.seaboardcorp.com,11781,Food Production,"Merriam, KS",9000 W. 67th St.,Merriam,KS,66202,...,"Chairman, President & Chief Executive Officer","9000 W. 67th St., Merriam, KS 66202",SEB,Seaboard Corporation,5379,-3.8,312.0,82.5,4755,3162.0
Health Care,454,Genesis Healthcare,http://www.genesishcc.com,82000,Health Care: Medical Facilities,"Kennett Square, PA",101 E. State St.,Kennett Square,PA,19348,...,Chief Executive Officer & Director,"101 E. State St., Kennett Square, PA 19348",GEN,"Genesis Healthcare, Inc.",5733,2.0,-64.0,11.7,5779,-490.0
"Hotels, Restaurants & Leisure",461,Wyndham Worldwide,http://www.wyndhamworldwide.com,37800,"Hotels, Casinos, Resorts","Parsippany, NJ",22 Sylvan Way,Parsippany,NJ,7054,...,Chairman & Chief Executive Officer,"22 Sylvan Way, Parsippany, NJ 07054",WYN,Wyndham Worldwide Corporation,5599,1.1,611.0,-0.2,9819,714.0
Household Products,474,Mattel,http://www.mattel.com,32000,"Toys, Sporting Goods","El Segundo, CA",333 Continental Blvd.,El Segundo,CA,90245,...,Chief Executive Officer & Director,"333 Continental Blvd., El Segundo, CA 90245",MAT,"Mattel, Inc.",5457,-4.3,318.0,-13.9,6494,2408.0
Industrials,445,Terex,http://www.terex.com,18100,Construction and Farm Machinery,"Westport, CT",200 Nyala Farm Rd.,Westport,CT,6880,...,"President, Chief Executive Officer & Director","200 Nyala Farm Rd., Westport, CT 06880",TEX,Terex Corporation,5841,-10.7,-176.1,-220.7,5007,1484.7
Materials,458,Owens Corning,http://www.owenscorning.com,16000,"Building Materials, Glass","Toledo, OH",1 Owens Corning Pkwy.,Toledo,OH,43659,...,"Chairman, President & Chief Executive Officer","1 Owens Corning Pkwy., Toledo, OH 43659",OC,Owens Corning,5677,6.1,393.0,19.1,7741,3849.0
Media,491,Liberty Media,http://www.libertymedia.com,3626,Entertainment,"Englewood, CO",12300 Liberty Blvd.,Englewood,CO,80112,...,"President, Chief Executive Officer & Director","12300 Liberty Blvd., Englewood, CO 80112",LSXMA,Liberty Media Corporation,5276,10.0,680.0,962.5,31377,11756.0
Motor Vehicles & Parts,447,Dana,http://www.dana.com,24900,Motor Vehicles and Parts,"Maumee, OH",3939 Technology Dr.,Maumee,OH,43537,...,"President, Chief Executive Officer & Director","3939 Technology Dr., Maumee, OH 43537",DAN,Dana Incorporated,5826,-3.9,640.0,302.5,4860,1157.0
Retailing,496,Michaels Cos.,http://www.michaels.com,31000,Specialty Retailers: Other,"Irving, TX",8000 Bent Branch Dr.,Irving,TX,75063,...,Chairman & Chief Executive Officer,"8000 Bent Branch Dr., Irving, TX 75063",MIK,"The Michaels Companies, Inc.",5197,5.8,378.2,4.2,2148,-1698.0
Technology,498,Yahoo,http://www.yahoo.com,8500,Internet Services and Retailing,"Sunnyvale, CA",701 First Ave.,Sunnyvale,CA,94089,...,"President, Chief Executive Officer & Director","701 First Ave., Sunnyvale, CA 94089",YHOO,Yahoo! Inc.,5169,4.0,-214.3,5.2,48083,31049.0
Telecommunications,485,Windstream Holdings,http://www.windstream.com,11870,Telecommunications,"Little Rock, AR",4001 Rodney Parham Rd.,Little Rock,AR,72212,...,"President, Chief Executive Officer & Director","4001 Rodney Parham Rd., Little Rock, AR 72212",WIN,"Windstream Holdings, Inc.",5387,-6.6,-383.5,"-1,499.60",11770,170.0
Transportation,438,Alaska Air Group,http://www.alaskaair.com,19112,Airlines,"Seattle, WA",19300 International Blvd.,Seattle,WA,98188,...,"Chairman, President & Chief Executive Officer","19300 International Blvd., Seattle, WA 98188",ALK,"Alaska Air Group, Inc.",5931,5.9,814.0,-4,9962,2931.0
Wholesalers,489,Airgas,http://www.airgas.com,17000,Wholesalers: Diversified,"Radnor, PA",259 N. Radnor-Chester Rd.,Radnor,PA,19087,...,Chief Executive Officer & Director,"259 N. Radnor-Chester Rd., Radnor, PA 19087",APA,"Airgas, Inc.",5314,0.2,337.5,-8.3,6135,2045.0